// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "08fcca11-009a-4bf1-8517-5c9c9b0b17fd");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1770476772);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1770476771);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "fdcb1cdb-a944-4689-b282-4567ae8cc5ad");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1770476770);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1770476770);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 163);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-v2-copy:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.impressionId", "{467c19da-78b8-4737-9eeb-67dcfeea1faa}");
user_pref("browser.newtabpage.activity-stream.telemetry.privatePing.enabled", true);
user_pref("browser.newtabpage.activity-stream.telemetry.privatePing.redactNewtabPing.enabled", true);
user_pref("browser.newtabpage.disableNewTabAsAddon", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "148.0.20251211.63751");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.profiles.enabled", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1770476771);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1770476772560");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1770498372560");
user_pref("browser.search.region", "HK");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1770476771");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260203190549");
user_pref("browser.startup.homepage_override.mstone", "147.0.3");
user_pref("browser.startup.lastColdStartupCheck", 1770476771);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbarbuttons.introduced.sidebar-button", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1770476771);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 6);
user_pref("captchadetection.lastSubmission", 1770476);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "d44f82df-57f8-4e3a-8049-be414d885faf");
user_pref("datareporting.dau.cachedUsageProfileID", "8585d62c-1963-408c-82c0-e9de05a8906e");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1770476771156");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "147.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "HK");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "17d6414e971f4e109a83413f37771b55");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260203190549");
user_pref("extensions.lastAppVersion", "147.0.3");
user_pref("extensions.lastPlatformVersion", "147.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_interventions", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"0f0b2400-c830-41fb-835d-f9496aa471d9\",\"formautofill@mozilla.org\":\"7e4bb8a8-ea7e-4753-abbd-f8eaca0726d1\",\"ipp-activator@mozilla.com\":\"f1be7f08-e09a-4748-b76f-46886d76de95\",\"pictureinpicture@mozilla.org\":\"3fbc5df1-f643-4e62-9e2f-de1e7a8f2b0b\",\"addons-search-detection@mozilla.com\":\"391af6b0-937e-4e0a-9444-d9dde44492f0\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"ad2bbd42-40f7-46a9-8b5e-d6c5e53a76aa\",\"default-theme@mozilla.org\":\"b920f7b1-ff44-4fd8-a849-07c447b813b8\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "3a7af600-aad6-46b4-89b2-3ba6b2381c23");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherWidth\":0,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks");
user_pref("sidebar.nimbus", "sidebar-14402-rollout:rollout-treatment");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.revamp", true);
user_pref("sidebar.revamp.defaultLauncherVisible", false);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("toolkit.profiles.storeID", "984b0348");
user_pref("toolkit.startup.last_success", 1770476769);
user_pref("toolkit.telemetry.cachedClientID", "d9d0d4d3-fb0b-4f76-bdeb-a0199889671e");
user_pref("toolkit.telemetry.cachedProfileGroupID", "8a416039-b95a-4f90-95f5-830cebefac54");
user_pref("toolkit.telemetry.previousBuildID", "20260203190549");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
