[mgr]
show_hidden = true

[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]

view = [{ run = 'zathura "$@"', orphan = true, for = "unix" }]

play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]

open = [{ run = 'libreoffice "$@"' }]

[open]
rules = [
  { mime = "text/*", use = "edit" },

  { mime = "application/pdf", use = "view" },
  { url = "*.pdf", use = "view" },

  { url = "*.mkv", use = "play" },
  { url = "*.mp4", use = "play" },
  { url = "*.avi", use = "play" },
  { url = "*.mov", use = "play" },
  { url = "*.webm", use = "play" },

  { url = "*.jpg", use = "view" },
  { url = "*.jpeg", use = "view" },
  { url = "*.png", use = "view" },
  { url = "*.gif", use = "view" },

  { url = "*.doc", use = "open" },
  { url = "*.docx", use = "open" },
  { url = "*.odt", use = "open" },
  { url = "*.pptx", use = "open" },
]

[preview]
max_width = 1980
max_height = 1080
